settings:
    timing:
        mode: daily
        days: 1
        ticks: 2000
    border:
        start:
            circular_border: true
            initial_size: 2000
        relocate:
            active: true
            distance: 100
            direction: north
        resize:
            active: false
            amount: 100
    announce:
        periodic:
            active: true
            interval: 1000
            message: This server runs ShiftingPerspectives. Your stuff isn't safe anymore...
        warn_before_shift:
            active: true
            ticks_before: 1200
            message: Shift coming soon. Watch out!
        warn_at_risk_users:
            active: true
            ticks_before: 1000
            message: You are about to be Shifted! Grab your stuff and move %s!