settings:
    timing:
        mode: daily
        days: 3
        ticks: 6000
    start_border:
        circular_border: true
        initial_size: 2000
    border:
        relocate:
            active: true
            shift_distance: 100
            shift_direction: north
        resize:
            active: false
            amount: 100
    announce:
        periodic:
            active: true
            interval: 1000
            message: This server runs ShiftingPerspectives. Your stuff ain't safe no more!
        warn_before_shift:
            active: true
            ticks_before: 1200
            message: Shift soon. Watch out!
        warn_at_risk_users:
            active: true
            warn_before: 1200
            message: You are in an area about to be swallowed up. MOVE YOUR ASS!